### ISSUE TITLE
JIRA comment template questions

### ISSUE THREAD

**Issue by robiter** [mamirov/jirareporter#11]
Hi,

What is the parameter i need to put in the custom template for Jira comments inorder for me to see the row:
"Chrome Tests : Test Failed: 1, Passed : 0" (with link) like in your default comment template. I cant seem to get this row on custom template with the examples you wrote.

and another question.

Is there a way to add a jirareporter build step after several steps in the build config? i mean, if i have several steps that execute several test plans, i want a jira report after every step to a different issue. is this possible?

**Comment by mamirov** [comment]
See wiki page in header "Template for JIRA comment", what your have defined params
https://github.com/mamirov/jirareporter/wiki/TeamCity-JIRA-Reporter-(ENG)

Also, i used for default template this scheme:
[ _build.type.name_ : _tests.results_ |_teamcity.server.url_/viewLog.html?buildId=_build.id_&tab=buildResultsDiv&buildTypeId=_build.type_]

Yes, you can use this plugin after every your build step for different issue, also, you can write issue for multi-reporting, how?
Choose "Issue ID Place" - Jira reporter, and write issues like this "ISSUE-1,ISSUE-2,ISSUE-3"
Else issue place is "VCS Comment", issues get more if related in VCS comment more.

**Comment by robiter** [comment]
Thanks for the fast response!

**Comment by mamirov** [comment]
If my answer resolve your question, please don`t forget close issue and rate this repo ;)
