### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by robiter** [mamirov/jirareporter#6]
Hi,
## After installing the plugin, when i add the build step i get this error:

Unexpected Error

This was not supposed to happen. Please provide the error details to your TeamCity server maintainer.
If you maintain this TeamCity installation please report this error to JetBrains.

Error message: /plugins/jirareporter/jirareporter.jsp (line: 18, column: 12) Attribute id invalid for tag textProperty according to TLD
TeamCity: 7.1 (build 23907)
Operating system: Windows 7 (6.1, x86)
Java: 1.6.0_31-b05 (Sun Microsystems Inc.)
## Servlet container: Apache Tomcat/7.0.23

Any ideas?

Thanks

**Comment by mamirov** [comment]
In TeamCity since 7.x version, maybe tag "textProperty" not support attribute "id", i see this tommorow, thanks for reporting.

**Comment by mamirov** [comment]
I updated plugin for this bug, download plugin from here and check correctly working plugin:
https://bitbucket.org/mamirov/jirareporter/issue-attachment/1/mamirov/jirareporter/1387425567.85/1/jirareporter.zip

**Comment by robiter** [comment]
Thanks! that fixed the problem.
